# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
    db_driver: orm

    mappings:
        musique_images:
            uri_prefix: '%musique_images%'
            upload_destination: '%kernel.project_dir%/public%musique_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false 

        album_images:
            uri_prefix: '%album_images%'
            upload_destination: '%kernel.project_dir%/public%album_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false 

        artist_images:
            uri_prefix: '%artist_images%'
            upload_destination: '%kernel.project_dir%/public%artist_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false 

        music_file:
            uri_prefix: '%music_file%'
            upload_destination: '%kernel.project_dir%/public%music_file%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false 

        article_images:
            uri_prefix: '%article_images%'
            upload_destination: '%kernel.project_dir%/public%article_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false 
