vich_uploader:
    db_driver: orm

    mappings:
        musique_image:
            uri_prefix: '%musique_images%'
            upload_destination: '%kernel.project_dir%/public%musique_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false 
